### ISSUE TITLE
incompatibility with Charm 1.17.1

### ISSUE THREAD

**Issue by sarifynna** [Tigereye504/passive-charms#1]
Hello! I found that having both of these mods breaks crafting somewhat. I made a short example video and have the lastest.log if that even helps.

fabric-api-0.39.2+1.17.jar
passivecharms-1.1.0.jar
charm-fabric-1.17-3.3.2.jar

https://drive.google.com/file/d/1QmHmKwGQ8UB1OvxZOf8D8yP_OGyrjuym/view?usp=sharing

**Comment by Tigereye504** [comment]
Resolved in 1.2.1
